
CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;

CREATE TABLE IF NOT EXISTS todo_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS todoItems (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    progress VARCHAR(5) NOT NULL
);

INSERT INTO todo_users (name, password) 
VALUES ('yamada','$2a$12$N/k4HeW.r1u3NLg9Q8piYOecakaLtmAdOVOIm7xJlHdcZ.tA2qMMW')
ON DUPLICATE KEY UPDATE name=VALUES(name);


CREATE USER IF NOT EXISTS '${DB_USER_READONLY}'@'%' IDENTIFIED BY '${DB_PASSWORD_READONLY}';
GRANT SELECT ON test_db.* TO '${DB_USER_READONLY}'@'%';

CREATE USER IF NOT EXISTS '${DB_USER_WRITEONLY}'@'%' IDENTIFIED BY '${DB_PASSWORD_WRITEONLY}';
GRANT SELECT, INSERT, UPDATE, DELETE ON test_db.* TO '${DB_USER_WRITEONLY}'@'%';

FLUSH PRIVILEGES;